pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('sonarQube'){
                 sh """mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                 -Dsonar.projectKey=Akomolafegrace_geo-app"""
                }
                
            }
        }
        stage("maven"){
            steps{
                sh 'mvn clean'
                sh 'mvn validate' 
                sh 'mvn compile' 
                sh 'mvn install' 
                sh 'mvn test' 
                sh 'mvn package'
            }
        }
        stage ('upload artifact'){
            steps{
                sh'curl -uadmin:APALKYmZCo8dMhFq6cvqwp3mgid -T \
                 target/bio*.jar \
                 "http://ec2-54-210-126-112.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
        stage ('docker login') {
            steps{
               sh """aws ecr get-login-password --region us-east-1 |\
                 docker login --username AWS --password-stdin\
                  940482416510.dkr.ecr.us-east-1.amazonaws.com"""
            }
        }
        stage ('docker image build') {
            steps{
                sh "docker build -t utc-app:v.${BUILD_ID} ."
                sh "docker build -t utc-app:latest ."
            }
        }
        stage ('Image tagging') {
            steps{
                sh "docker tag utc-app:v.${BUILD_ID} 940482416510.dkr.ecr.us-east-1.amazonaws.com/utc-app:v.${BUILD_ID}"
                sh "docker tag utc-app:latest 940482416510.dkr.ecr.us-east-1.amazonaws.com/utc-app:latest"
            }   
        }
        stage ('push image') {
            steps{
                sh "docker push 940482416510.dkr.ecr.us-east-1.amazonaws.com/utc-app:latest"
                sh "docker push 940482416510.dkr.ecr.us-east-1.amazonaws.com/utc-app:v.${BUILD_ID}"
            }
        }
            
    }
}